# 乱数

### np.randomはグローバルにランダムシードを変える

In [1]:
import numpy as np
print(np.random.rand())
print(np.random.rand())

0.1202621537264914
0.36139224730943154


In [2]:
np.random.rand(2,3)

array([[0.27865862, 0.16850994, 0.91428474],
       [0.74972678, 0.32337131, 0.2189928 ]])

In [3]:
np.random.rand(5)

array([0.28425916, 0.58019363, 0.02561772, 0.39741331, 0.17660295])

In [4]:
np.random.randint(5)

3

In [5]:
np.random.randint(10, 20)

18

In [6]:
np.random.randint(5, size=(3,3))

array([[2, 0, 0],
       [0, 0, 3],
       [4, 3, 4]])

### 再現性と乱数の種

乱数の種を指定すると決まった乱数列が生成される

In [7]:
np.random.seed(10)
print(np.random.rand(5))
np.random.seed(10)
print(np.random.rand(5))

[0.77132064 0.02075195 0.63364823 0.74880388 0.49850701]
[0.77132064 0.02075195 0.63364823 0.74880388 0.49850701]


### インスタンスごとに異なる乱数発生器をもたせるには、np.random.RandomStateクラスを使う

RandomStateクラス

In [8]:
rs = np.random.RandomState(10)
print(rs.rand(5))
print(rs.rand(5))

[0.77132064 0.02075195 0.63364823 0.74880388 0.49850701]
[0.22479665 0.19806286 0.76053071 0.16911084 0.08833981]


クラスにRandomStateを与える

In [9]:
# 種としてNoneを与えると乱数生成器の再現性を保証しない
class Dice:
    def __init__(self, random_seed=None):
        self.random_state_ = np.random.RandomState(random_seed)
        self.sum_ = 0
        
    def throw(self):
        self.sum_ += self.random_state_.randint(1,7)
        
    def get_sum(self):
        return self.sum_

このクラスは,インスタンス時に引数を与えないと、再現性のない結果になり、引数を与えるとそれを種として再現性を持つ

In [10]:
d1 = Dice(123)
d2 = Dice(123)

for _ in range(10):
    d1.throw()
    d2.throw()

同じ乱数列が発生し、和は同じ結果になる

In [11]:
print(d1.get_sum())
print(d2.get_sum())

34
34
